jobs: 100
cluster: "sbatch -p fm-bigmem-1,fm-bigmem-2,fm-bigmem-3,fm-bigmem-4 -t {resources.time_min} --mem={resources.mem_mb} --cpus-per-task {resources.cpus} -o run/logs_slurm/{rule}_{wildcards}.%j.out -e run/logs_slurm/{rule}_{wildcards}.%j.err"
resources: [cpus=555, mem_mb=16810980]
